/// English -> French country names for the teams that appear in the feed.
/// Used for display only; the English name is kept for API-Football lookups.
const Map<String, String> _frCountries = {
  'Algeria': 'Algérie',
  'Argentina': 'Argentine',
  'Australia': 'Australie',
  'Austria': 'Autriche',
  'Belgium': 'Belgique',
  'Bosnia & Herzegovina': 'Bosnie-Herzégovine',
  'Brazil': 'Brésil',
  'Canada': 'Canada',
  'Cape Verde': 'Cap-Vert',
  'Colombia': 'Colombie',
  'Croatia': 'Croatie',
  'Curaçao': 'Curaçao',
  'Curacao': 'Curaçao',
  'Czech Republic': 'République tchèque',
  'DR Congo': 'RD Congo',
  'Ecuador': 'Équateur',
  'Egypt': 'Égypte',
  'England': 'Angleterre',
  'France': 'France',
  'Germany': 'Allemagne',
  'Ghana': 'Ghana',
  'Haiti': 'Haïti',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Ivory Coast': 'Côte d\'Ivoire',
  'Japan': 'Japon',
  'Jordan': 'Jordanie',
  'Mexico': 'Mexique',
  'Morocco': 'Maroc',
  'Netherlands': 'Pays-Bas',
  'New Zealand': 'Nouvelle-Zélande',
  'Norway': 'Norvège',
  'Panama': 'Panama',
  'Paraguay': 'Paraguay',
  'Portugal': 'Portugal',
  'Qatar': 'Qatar',
  'Saudi Arabia': 'Arabie Saoudite',
  'Scotland': 'Écosse',
  'Senegal': 'Sénégal',
  'South Africa': 'Afrique du Sud',
  'South Korea': 'Corée du Sud',
  'Spain': 'Espagne',
  'Sweden': 'Suède',
  'Switzerland': 'Suisse',
  'Tunisia': 'Tunisie',
  'Turkey': 'Turquie',
  'USA': 'États-Unis',
  'Uruguay': 'Uruguay',
  'Uzbekistan': 'Ouzbékistan',
};

/// Returns the French country name, or the original if it isn't in the map.
String frCountry(String englishName) =>
    _frCountries[englishName] ?? englishName;
